language: node_js
sudo: false

node_js:
  - "0.12"
  - "4"
  - "5"
  - "6"

before_script:
  - mkdir -p nats-streaming-server
  - wget https://github.com/nats-io/nats-streaming-server/releases/download/v0.2.2/nats-streaming-server-linux-amd64.zip -qO - | tar -zxvC nats-streaming-server/

